refactor(edit): improve code quality

diff --git a/scripts/edit b/scripts/edit
--- a/scripts/edit
+++ b/scripts/edit
@@ -5,23 +5,56 @@
 # files and scripts
 #
 
+function main() {
+	parsed_args=$(getopt -o h -l help -n 'edit' -- "$@")
+	getopt_exit_code=$?
 
-TARGET="$1"
+	if [ $getopt_exit_code -ne 0 ] ; then
+		exit 1
+	fi
 
-case "$1" in
-	alacritty ) vim ~/.alacritty.yml ;;
-	vim ) vim ~/.vimrc ;;
-	zsh ) vim ~/.zshrc ;;
-	zprofile ) vim ~/.zprofile ;;
-	xres ) vim ~/.Xresources ;;
-	xinit ) vim ~/.xinitrc ;;	
-	git ) vim ~/.gitconfig ;;
-	htop ) vim ~/.config/htop/htoprc ;;
-	i3 ) vim ~/.config/i3/config ;;
-	polybar ) vim ~/.config/polybar/config ;;
-	polylaunch ) vim ~/.config/polybar/launch.sh ;;
-	picom ) vim ~/.config/picom/picom.conf ;;
-	rofi ) vim ~/.config/rofi/theme.rasi ;;
-	dunst ) vim ~/.config/dunst/dunstrc ;;
-	* ) vim "$BASH_SOURCE" ;;
-esac
+	eval set -- "$parsed_args" 
+
+	while :; do
+		case "$1" in
+			-h | --help ) show_help; exit 1 ;;
+			-- ) shift; break ;;
+			* ) break ;;
+		esac
+	done
+
+	target="$1"
+
+	[ -z "$target" ] && die 'target cannot be empty'
+
+	case "$target" in
+		alacritty ) vim ~/.alacritty.yml ;;
+		vim ) vim ~/.vimrc ;;
+		zsh ) vim ~/.zshrc ;;
+		zprofile ) vim ~/.zprofile ;;
+		xres ) vim ~/.Xresources ;;
+		xinit ) vim ~/.xinitrc ;;	
+		git ) vim ~/.gitconfig ;;
+		htop ) vim ~/.config/htop/htoprc ;;
+		i3 ) vim ~/.config/i3/config ;;
+		polybar ) vim ~/.config/polybar/config ;;
+		polylaunch ) vim ~/.config/polybar/launch.sh ;;
+		picom ) vim ~/.config/picom/picom.conf ;;
+		rofi ) vim ~/.config/rofi/theme.rasi ;;
+		dunst ) vim ~/.config/dunst/dunstrc ;;
+		self ) vim "$BASH_SOURCE" ;;
+	esac
+}
+
+function die() {
+	printf "error: %s\n" "$@" >&2
+	exit 1
+}
+
+function show_help() {
+	echo Usage: edit [ -h ] TARGET
+	echo Options are:
+	echo '     -h | --help                    display this message and exit'
+}
+
+main "$@"
