refactor(sltx): improve code quality

diff --git a/scripts/sltx b/scripts/sltx
--- a/scripts/sltx
+++ b/scripts/sltx
@@ -5,17 +5,47 @@
 # and copies it to the clipboard
 #
 
-temp=$(mktemp -d)
+function main() {
+	parsed_args=$(getopt -o h -l help -n 'sltx' -- "$@")
+	getopt_exit_code=$?
 
-cd $temp
-scrot -s selection.png
+	if [ $getopt_exit_code -ne 0 ] ; then
+		exit 1
+	fi
 
-if ! test -f selection.png ; then
-	exit 1;
-fi
+	eval set -- "$parsed_args" 
 
-tesseract selection.png result 2>/dev/null>&2
-cat result.txt | xclip -i -sel clipboard
-rm -rf "$temp"
+	while :; do
+		case "$1" in
+			-h | --help ) show_help; exit 1 ;;
+			-- ) shift; break ;;
+			* ) break ;;
+		esac
+	done
 
-notify-send 'success' 'text copied to the clipboard'
+	temp=$(mktemp -d)
+
+	cd $temp
+	scrot -s selection.png
+
+	[ -f selection.png ] || die 'selection cancelled'
+
+	tesseract selection.png result 2>/dev/null>&2
+	cat result.txt | xclip -i -sel clipboard
+	rm -rf "$temp"
+
+	notify-send 'success' 'text copied to the clipboard'
+}
+
+function die() {
+	printf "error: %s\n" "$@" >&2
+	exit 1
+}
+
+function show_help() {
+	echo Usage: sltx [ -h ]
+	echo Options are:
+	echo '     -h | --help                    display this message and exit'
+}
+
+main "$@"
